# Generated by Django 6.0.5 on 2026-05-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributosAnexos',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Atributo Anexo',
                'verbose_name_plural': 'Atributos Anexos',
                'db_table': 'atributos_anexos',
            },
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id_auditor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_auditor', models.CharField(max_length=100)),
                ('documento_auditor', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Auditor',
                'verbose_name_plural': 'Auditores',
                'db_table': 'auditores',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('data_auditoria', models.DateField()),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('INCONCLUIDA', 'Inconcluída'), ('CONCLUIDA', 'Concluída')], default='INCONCLUIDA', max_length=20)),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'db_table': 'auditorias',
            },
        ),
        migrations.CreateModel(
            name='CapacidadeOperacional',
            fields=[
                ('id_capacidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Capacidade Operacional',
                'verbose_name_plural': 'Capacidades Operacionais',
                'db_table': 'capacidades_operacionais',
            },
        ),
        migrations.CreateModel(
            name='ConceitoSI',
            fields=[
                ('id_conceito', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Conceito de Segurança da Informação',
                'verbose_name_plural': 'Conceitos de Segurança da Informação',
                'db_table': 'conceitos_si',
            },
        ),
        migrations.CreateModel(
            name='Controle27002',
            fields=[
                ('id_controle', models.AutoField(primary_key=True, serialize=False)),
                ('indice_norma', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Controle 27002',
                'verbose_name_plural': 'Controles 27002',
                'db_table': 'controles_27002',
            },
        ),
        migrations.CreateModel(
            name='Controle27701',
            fields=[
                ('id_controle', models.AutoField(primary_key=True, serialize=False)),
                ('indice_norma', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('anexoB', models.CharField(blank=True, max_length=255, null=True)),
                ('orientacao_anexoB', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Controle 27701',
                'verbose_name_plural': 'Controles 27701',
                'db_table': 'controles_27701',
            },
        ),
        migrations.CreateModel(
            name='DominioSeguranca',
            fields=[
                ('id_dominio', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('propriedade_inclui', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Domínio de Segurança',
                'verbose_name_plural': 'Domínios de Segurança',
                'db_table': 'dominios_seguranca',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('porte', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Evidencias27002',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='evidencias/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Evidência 27002',
                'verbose_name_plural': 'Evidências 27002',
                'db_table': 'evidencias_27002',
            },
        ),
        migrations.CreateModel(
            name='Evidencias27701',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='evidencias/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Evidência 27701',
                'verbose_name_plural': 'Evidências 27701',
                'db_table': 'evidencias_27701',
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id_norma', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('versao', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'db_table': 'normas',
            },
        ),
        migrations.CreateModel(
            name='PropriedadeSI',
            fields=[
                ('id_propriedade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Propriedade de Segurança da Informação',
                'verbose_name_plural': 'Propriedades de Segurança da Informação',
                'db_table': 'propriedades_si',
            },
        ),
        migrations.CreateModel(
            name='RespostasAuditoria27002',
            fields=[
                ('id_resposta27002', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('possui_andamento', models.BooleanField(default=False)),
                ('situacao', models.CharField(choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('NAO_APLICA', 'Não Aplica')], max_length=20)),
            ],
            options={
                'verbose_name': 'Resposta de Auditoria 27002',
                'verbose_name_plural': 'Respostas de Auditoria 27002',
                'db_table': 'respostas_auditoria_27002',
            },
        ),
        migrations.CreateModel(
            name='RespostasAuditoria27701',
            fields=[
                ('id_resposta27701', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('possui_andamento', models.BooleanField(default=False)),
                ('situacao', models.CharField(choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('NAO_APLICA', 'Não Aplica')], max_length=20)),
            ],
            options={
                'verbose_name': 'Resposta de Auditoria 27701',
                'verbose_name_plural': 'Respostas de Auditoria 27701',
                'db_table': 'respostas_auditoria_27701',
            },
        ),
        migrations.CreateModel(
            name='TemaControle',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Tema de Controle',
                'verbose_name_plural': 'Temas de Controle',
                'db_table': 'temas_controle',
            },
        ),
        migrations.CreateModel(
            name='TipoControle',
            fields=[
                ('id_tipo_controle', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Tipo de Controle',
                'verbose_name_plural': 'Tipos de Controle',
                'db_table': 'tipos_controle',
            },
        ),
        migrations.CreateModel(
            name='TipoControleAnexo',
            fields=[
                ('id_tipo_controle_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Controle Anexo',
                'verbose_name_plural': 'Tipos de Controle Anexos',
                'db_table': 'tipos_controle_anexos',
            },
        ),
    ]
