# Generated by Django 6.0.5 on 2026-05-21 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='controles.auditor'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='capacidades_operacionais',
            field=models.ManyToManyField(blank=True, related_name='controles', to='controles.capacidadeoperacional'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='conceitos_si',
            field=models.ManyToManyField(blank=True, related_name='controles', to='controles.conceitosi'),
        ),
        migrations.AddField(
            model_name='controle27701',
            name='atributos_anexos',
            field=models.ManyToManyField(blank=True, related_name='controles_27701', to='controles.atributosanexos'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='dominios_seguranca',
            field=models.ManyToManyField(blank=True, related_name='controles', to='controles.dominioseguranca'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='controles.empresa'),
        ),
        migrations.AddField(
            model_name='controle27701',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_27701', to='controles.norma'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='controles.norma'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='controles.norma'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='propriedades_si',
            field=models.ManyToManyField(blank=True, related_name='controles', to='controles.propriedadesi'),
        ),
        migrations.AddField(
            model_name='respostasauditoria27002',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_27002', to='controles.auditoria'),
        ),
        migrations.AddField(
            model_name='respostasauditoria27002',
            name='controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_auditoria', to='controles.controle27002'),
        ),
        migrations.AddField(
            model_name='evidencias27002',
            name='resposta_auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='controles.respostasauditoria27002'),
        ),
        migrations.AddField(
            model_name='respostasauditoria27701',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_27701', to='controles.auditoria'),
        ),
        migrations.AddField(
            model_name='respostasauditoria27701',
            name='controle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_auditoria', to='controles.controle27701'),
        ),
        migrations.AddField(
            model_name='evidencias27701',
            name='resposta_auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='controles.respostasauditoria27701'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='temas_controle',
            field=models.ManyToManyField(blank=True, related_name='controles', to='controles.temacontrole'),
        ),
        migrations.AddField(
            model_name='controle27002',
            name='tipos_controle',
            field=models.ManyToManyField(blank=True, related_name='controles', to='controles.tipocontrole'),
        ),
        migrations.AddField(
            model_name='controle27701',
            name='tipos_controle_anexo',
            field=models.ManyToManyField(blank=True, related_name='controles_27701', to='controles.tipocontroleanexo'),
        ),
        migrations.AlterUniqueTogether(
            name='controle27002',
            unique_together={('norma', 'indice_norma')},
        ),
        migrations.AlterUniqueTogether(
            name='controle27701',
            unique_together={('norma', 'indice_norma')},
        ),
    ]
